// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1XuG1Pmm7C-oFEZLI3DdHEXlHNWkxaM',
    appId: '1:302040267081:web:77d0a43e9025026fd18298',
    messagingSenderId: '302040267081',
    projectId: 'note-ai-d7ac8',
    authDomain: 'note-ai-d7ac8.firebaseapp.com',
    storageBucket: 'note-ai-d7ac8.firebasestorage.app',
    measurementId: 'G-X1SWM02DNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnIzhZikNxjXnAcdfyYuino5Fj5OdQ5I',
    appId: '1:302040267081:android:84b44d23205bd4a8d18298',
    messagingSenderId: '302040267081',
    projectId: 'note-ai-d7ac8',
    storageBucket: 'note-ai-d7ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMiyXhvnFbkY2uAb6fytI5tsurzLEHOdA',
    appId: '1:302040267081:ios:6c7545fb6d9b1153d18298',
    messagingSenderId: '302040267081',
    projectId: 'note-ai-d7ac8',
    storageBucket: 'note-ai-d7ac8.firebasestorage.app',
    iosBundleId: 'com.flutter.noteAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMiyXhvnFbkY2uAb6fytI5tsurzLEHOdA',
    appId: '1:302040267081:ios:6c7545fb6d9b1153d18298',
    messagingSenderId: '302040267081',
    projectId: 'note-ai-d7ac8',
    storageBucket: 'note-ai-d7ac8.firebasestorage.app',
    iosBundleId: 'com.flutter.noteAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt1XuG1Pmm7C-oFEZLI3DdHEXlHNWkxaM',
    appId: '1:302040267081:web:8463d3cfa270d1acd18298',
    messagingSenderId: '302040267081',
    projectId: 'note-ai-d7ac8',
    authDomain: 'note-ai-d7ac8.firebaseapp.com',
    storageBucket: 'note-ai-d7ac8.firebasestorage.app',
    measurementId: 'G-8CKS7FBX7K',
  );
}
